# Base image
FROM python:3.12-slim

# Set workdir
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


RUN apt-get update && apt-get install -y nodejs npm curl

WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend ./

WORKDIR /app
COPY . .

RUN apt-get install -y supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 3000 8000 10000

CMD ["supervisord", "-n"]
